export const projects = [
  {
    title: "Dalle Social",
    description:
      "Create images using AI and share them with the community. Enter a prompt with your idea for an image or use the 'Surprise Me!' button, to generate a random prompt",
    image: "/images/dalle-image.png",
    tags: [
      "Dalle",
      "Mongoose",
      "Node",
      "React",
      "Vite",
      "OpenAI",
      "TailwindCSS",
    ],
    source: "https://github.com/Juth7/dalle-social",
    visit: "https://dalle-social.vercel.app/",
    id: 0,
  },
  {
    title: "Customizer ThreeJs",
    description:
      "Web to Customize a T-shirt with or without logo,with option to generate with AI",
    image: "/images/Threejs-customize.png",
    tags: [
      "ThreeJs",
      "Mongoose",
      "Express",
      "React",
      "Node",
      "Framer-motion",
      "TailwindCSS",
    ],
    source: "https://github.com/Juth7/customizer-threejs",
    visit: "https://labellacollezione.com/",
    id: 1,
  },
  {
    title: "TRAVEL APP",
    description:
      "Travel App created with MongoDB, Express, React, Redux, Node and TailwindCSS. It allows users to register, login, buy a package, view details, search by name, package, detail or any word, filter by price and location. Needs authorization depending on the user. Admins can ban and eliminate users, add and edit packages and view all users.",
    image: "/images/TravelApp.jpg",
    tags: [
      "Mongo",
      "Mongoose",
      "Express",
      "React",
      "Node",
      "Redux",
      "TailwindCSS",
    ],
    source: "https://github.com/Juth7/TravelApp",
    visit: "https://travel-app-lac.vercel.app/",
    id: 2,
  },
  {
    title: "FOOD APP",
    description:
      "Single Page Application using React, Redux, Node.js, Express and PostgreSQL. This app is a food app. It allows users to look for food recipes, add recipes, filter by diet,search for recipes by name, and view the recipes they have created.",
    image: "/images/FoodApp.png",
    tags: [
      "Express",
      "React",
      "Node",
      "Redux",
      "PostgreSQL",
      "JavaScript",
      "Sequelize",
    ],
    source: "https://github.com/Juth7/PI-FOOD",
    visit: "https://juth-food.vercel.app/home",
    id: 3,
  },
  {
    title: "POKEMON APP",
    description:
      "Single Page Application using React, Redux, Node.js, Express and PostgreSQL. This app is a pokemon app. It allows users to look for pokemons, filter by type and creation and create new pokemons.",
    image: "/images/PokemonApp.jpg",
    tags: [
      "Express",
      "React",
      "Node",
      "Redux",
      "PostgreSQL",
      "JavaScript",
      "Sequelize",
    ],
    source: "https://github.com/Juth7/PI-Pokemon",
    visit: "https://juth-pokemon.vercel.app/home",
    id: 4,
  },
  {
    title: "WEATHER APP",
    description:
      "Application using React and Bootstrap. This app is a weather app. It allows users to look for cities, countries and check their weather. You can also see the temperature, winds, clouds, longitude and latitude",
    image: "/images/WeatherApp.jpg",
    tags: ["React", "Bootstrap"],
    source: "https://github.com/Juth7/weather-app",
    visit: "https://juth-weather-app.vercel.app/",
    id: 5,
  },
  // {
  //   title: "CAlCULATOR",
  //   description:
  //     "This is a calculator created with Typescript. It allows users to add,   subtract, multiply and divide numbers. It also allows users to save and delete operations.",
  //   image: "/images/4.jpg",
  //   tags: ["React", "TypeScript"],
  //   source: "https://google.com",
  //   visit: "https://google.com",
  //   id: 4,
  // },
];

export const TimeLineData = [
  { year: 2021, text: "Started the Bootcamp from Henry " },
  { year: 2021, text: "Worked as a Teacher Assistant" },
  { year: 2021, text: "Created My First App, Weather App" },
  { year: 2021, text: "Created My First SPA with Pokemon" },
  { year: 2022, text: "Created My Second SPA with Food Recipes" },
  { year: 2022, text: "Participated on a group project, Travel App" },
  { year: 2022, text: "Graduated from SoyHenry" },
  { year: 2022, text: "Started to Work at Tagwizz" },  
  { year: 2022, text: "Started to Work at Newe" },  
  { year: 2023, text: "Created New Proyects using AI and ThreeJS" },  
  { year: 2023, text: "Enrolled in courses in Web Development" },  
];
